version: 2.0

workflows:
  ios:
    name: iOS Build Workflow
    max_build_duration: 120  # Tiempo máximo de construcción en minutos
    steps:
      - checkout

      - name: Install Python dependencies
        run:
          name: Install dependencies
          command: |
            pip install buildozer cython

      - name: Build iOS app
        run:
          name: Build app
          command: |
            buildozer ios debug

      - name: Upload IPA file
        artifacts:
          - bin/*.ipa
