version: 2.1

workflows:
  ios_build:
    name: Build iOS App
    environment:
      xcode: '14.2'
    scripts:
      - name: Checkout source
        script: |
          git clone https://github.com/your-repo/your-app.git
      - name: Install dependencies
        script: |
          pip install buildozer cython
      - name: Build iOS app
        script: |
          buildozer ios debug
    artifacts:
      - path: bin/*.ipa
        type: ipa
