version: 2.0

workflows:
  ios:
    name: iOS Build Workflow
    max_build_duration: 120  # Tiempo máximo de construcción en minutos
    steps:
      - name: Checkout code
        action: checkout

      - name: Install Python dependencies
        action: run
        command: |
          pip install buildozer
          pip install cython

      - name: Build iOS app
        action: run
        command: |
          buildozer ios debug

      - name: Upload build artifacts
        action: upload
        path: bin/*.ipa

      # Si tienes configuraciones adicionales, puedes agregarlas aquí.
